### ISSUE TITLE
mamba 2.4 segfaults on Manjaro when it connects to JACK 

### ISSUE THREAD

**Issue by SpotlightKid** [brummer10/Mamba#52]
```
$ gcc -v
Es werden eingebaute Spezifikationen verwendet.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/lto-wrapper
Ziel: x86_64-pc-linux-gnu
Konfiguriert mit: /build/gcc/src/gcc/configure --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror
Thread-Modell: posix
Unterstützte LTO-Kompressionsalgorithmen: zlib zstd
gcc-Version 12.2.1 20230201 (GCC) 
```

```
$ gdb src/build/mamba 
GNU gdb (GDB) 13.1
[...]
]Reading symbols from src/build/mamba...
(gdb) run
Starting program: /home/chris/work/archlinux-proaudio/packages/mamba/src/Mamba_2.4/src/build/mamba 

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
[Thread debugging using libthread_db enabled]                                                                                                                                                 
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff60d46c0 (LWP 5623)]                                                                                                                                                        
[New Thread 0x7ffff58d36c0 (LWP 5624)]
[New Thread 0x7ffff57246c0 (LWP 5625)]
Samplerate 48000Hz 
[New Thread 0x7ffff56916c0 (LWP 5626)]
Buffersize is 256 samples 
jack running with realtime priority

Thread 1 "mamba" received signal SIGSEGV, Segmentation fault.
0x00007ffff74a55de in pthread_setschedparam () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff74a55de in pthread_setschedparam () at /usr/lib/libc.so.6
#1  0x00005555555bbb5c in xalsa::XAlsa::xalsa_set_priority(int) (this=0x7fffffffba50, priority=75) at XAlsa.cpp:131
#2  0x000055555557de2d in operator()(int) const (__closure=0x7fffffffc680, p=75) at MidiKeyBoard.cpp:3465
#3  0x0000555555580ec4 in std::__invoke_impl<void, main(int, char**)::<lambda(int)>&, int>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/12.2.1/bits/invoke.h:61
#4  0x0000555555580303 in std::__invoke_r<void, main(int, char**)::<lambda(int)>&, int>(struct {...} &) (__fn=...) at /usr/include/c++/12.2.1/bits/invoke.h:111
#5  0x000055555557f643 in std::_Function_handler<void(int), main(int, char**)::<lambda(int)> >::_M_invoke(const std::_Any_data &, int &&) (__functor=..., __args#0=@0x7fffffffb574: 75)
    at /usr/include/c++/12.2.1/bits/std_function.h:290
#6  0x00005555555c1ddc in std::function<void (int)>::operator()(int) const (this=0x7fffffffc680, __args#0=75) at /usr/include/c++/12.2.1/bits/std_function.h:591
#7  0x00005555555beba2 in xjack::XJack::init_jack() (this=0x7fffffffc620) at XJack.cpp:175
#8  0x000055555557e26c in main(int, char**) (argc=1, argv=0x7fffffffccc8) at MidiKeyBoard.cpp:3477
```

**Comment by brummer10** [comment]
mmm, that is really strange. 
There have nothing changed in that since v2.3
However, I've changed that now to hopefully works as expected, please checkout from head and let me know if it works now. If so I'll prepare a new v2.5 release.

regards
hermann

**Comment by SpotlightKid** [comment]
FWIW, I asked someone else to confirm the segfault and it also happens for them.

It seems fixed in Git, mamba starts normally again.

**Comment by brummer10** [comment]
Hi Chris 
Thanks for confirming that it works now. 
A new release (v2.5) is out now

regards
hermann
